package constant

const (
	PROGRAM_ID    = "PROGRAM-ID"
	AUTHOR        = "AUTHOR"
	INSTALLATION  = "INSTALLATION"
	DATE_WRITTEN  = "DATE-WRITTEN"
	DATE_COMPILED = "DATE-COMPILED"
	SECURITY      = "SECURITY"
	ENVIRONMENT   = "ENVIRONMENT"
	DATA          = "DATA"
	PROCEDURE     = "PROCEDURE"
	REMARKS       = "REMARKS"
)
