// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: cobol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Paragraph_ProgramId_Type int32

const (
	Paragraph_ProgramId_PROGRAM           Paragraph_ProgramId_Type = 0
	Paragraph_ProgramId_COMMON_PROGRAM    Paragraph_ProgramId_Type = 1
	Paragraph_ProgramId_INITIAL_PROGRAM   Paragraph_ProgramId_Type = 2
	Paragraph_ProgramId_RECURSIVE_PROGRAM Paragraph_ProgramId_Type = 3
	Paragraph_ProgramId_PROTOTYPE         Paragraph_ProgramId_Type = 4
)

// Enum value maps for Paragraph_ProgramId_Type.
var (
	Paragraph_ProgramId_Type_name = map[int32]string{
		0: "PROGRAM",
		1: "COMMON_PROGRAM",
		2: "INITIAL_PROGRAM",
		3: "RECURSIVE_PROGRAM",
		4: "PROTOTYPE",
	}
	Paragraph_ProgramId_Type_value = map[string]int32{
		"PROGRAM":           0,
		"COMMON_PROGRAM":    1,
		"INITIAL_PROGRAM":   2,
		"RECURSIVE_PROGRAM": 3,
		"PROTOTYPE":         4,
	}
)

func (x Paragraph_ProgramId_Type) Enum() *Paragraph_ProgramId_Type {
	p := new(Paragraph_ProgramId_Type)
	*p = x
	return p
}

func (x Paragraph_ProgramId_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Paragraph_ProgramId_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cobol_proto_enumTypes[0].Descriptor()
}

func (Paragraph_ProgramId_Type) Type() protoreflect.EnumType {
	return &file_cobol_proto_enumTypes[0]
}

func (x Paragraph_ProgramId_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Paragraph_ProgramId_Type.Descriptor instead.
func (Paragraph_ProgramId_Type) EnumDescriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{5, 0, 0}
}

type Source_Type int32

const (
	Source_CODE    Source_Type = 0
	Source_COMMENT Source_Type = 1
	Source_DEBUG   Source_Type = 2
)

// Enum value maps for Source_Type.
var (
	Source_Type_name = map[int32]string{
		0: "CODE",
		1: "COMMENT",
		2: "DEBUG",
	}
	Source_Type_value = map[string]int32{
		"CODE":    0,
		"COMMENT": 1,
		"DEBUG":   2,
	}
)

func (x Source_Type) Enum() *Source_Type {
	p := new(Source_Type)
	*p = x
	return p
}

func (x Source_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cobol_proto_enumTypes[1].Descriptor()
}

func (Source_Type) Type() protoreflect.EnumType {
	return &file_cobol_proto_enumTypes[1]
}

func (x Source_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source_Type.Descriptor instead.
func (Source_Type) EnumDescriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{11, 0}
}

// CompilationGroup
//
// A structured compilation group consists of zero, one, or more compilation units that have been processed by text
// manipulation.
type CompilationGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*CompilationUnit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *CompilationGroup) Reset() {
	*x = CompilationGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompilationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationGroup) ProtoMessage() {}

func (x *CompilationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationGroup.ProtoReflect.Descriptor instead.
func (*CompilationGroup) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{0}
}

func (x *CompilationGroup) GetUnits() []*CompilationUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

// CompilationUnit
//
// A compilation unit may contain one or more source units, depending on the type of definition.
// A compilation unit is one of the following:
//
//	a program-prototype definition
//	a function-prototype definition
//	a program definition for an outermost program
//	a class definition
//	an interface definition
//	a function definition
type CompilationUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*SourceUnit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *CompilationUnit) Reset() {
	*x = CompilationUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompilationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationUnit) ProtoMessage() {}

func (x *CompilationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationUnit.ProtoReflect.Descriptor instead.
func (*CompilationUnit) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{1}
}

func (x *CompilationUnit) GetUnits() []*SourceUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

// SourceUnit
//
// A source unit begins with an identification division and ends with an end marker or the end of the compilation
// group. A source unit includes any contained source units. The following are source units:
//
//	an outermost program-definition, including its contained program-definitions
//	a contained program-definition, including its contained program-definitions
//	a program-prototype-definition
//	a function-definition
//	a function-prototype-definition
//	a class-definition, including its factory definition and instance definition
//	a factory definition, including its method definitions
//	an instance definition, including its method definitions
//	a method definition
//	an interface definition, including its method prototypes
type SourceUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Divisions
	//
	// A source unit may contain one or more divisions, specified in the following order:
	//
	//	identification division
	//	environment division
	//	data division
	//	procedure division
	Divisions []*Division `protobuf:"bytes,1,rep,name=divisions,proto3" json:"divisions,omitempty"`
	// Units Contained source units
	//
	// Source units may be contained directly or indirectly.
	Units []*SourceUnit `protobuf:"bytes,2,rep,name=units,proto3" json:"units,omitempty"`
	// Sources origion source
	Sources []*Source `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *SourceUnit) Reset() {
	*x = SourceUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceUnit) ProtoMessage() {}

func (x *SourceUnit) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceUnit.ProtoReflect.Descriptor instead.
func (*SourceUnit) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{2}
}

func (x *SourceUnit) GetDivisions() []*Division {
	if x != nil {
		return x.Divisions
	}
	return nil
}

func (x *SourceUnit) GetUnits() []*SourceUnit {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *SourceUnit) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Division struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOf:
	//
	//	*Division_Identification
	//	*Division_Environment
	//	*Division_Data
	//	*Division_Procedure
	OneOf isDivision_OneOf `protobuf_oneof:"one_of"`
}

func (x *Division) Reset() {
	*x = Division{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Division) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Division) ProtoMessage() {}

func (x *Division) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Division.ProtoReflect.Descriptor instead.
func (*Division) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{3}
}

func (m *Division) GetOneOf() isDivision_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (x *Division) GetIdentification() *Identification {
	if x, ok := x.GetOneOf().(*Division_Identification); ok {
		return x.Identification
	}
	return nil
}

func (x *Division) GetEnvironment() *Environment {
	if x, ok := x.GetOneOf().(*Division_Environment); ok {
		return x.Environment
	}
	return nil
}

func (x *Division) GetData() *Data {
	if x, ok := x.GetOneOf().(*Division_Data); ok {
		return x.Data
	}
	return nil
}

func (x *Division) GetProcedure() *Procedure {
	if x, ok := x.GetOneOf().(*Division_Procedure); ok {
		return x.Procedure
	}
	return nil
}

type isDivision_OneOf interface {
	isDivision_OneOf()
}

type Division_Identification struct {
	Identification *Identification `protobuf:"bytes,1,opt,name=identification,proto3,oneof"`
}

type Division_Environment struct {
	Environment *Environment `protobuf:"bytes,2,opt,name=environment,proto3,oneof"`
}

type Division_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Division_Procedure struct {
	Procedure *Procedure `protobuf:"bytes,4,opt,name=procedure,proto3,oneof"`
}

func (*Division_Identification) isDivision_OneOf() {}

func (*Division_Environment) isDivision_OneOf() {}

func (*Division_Data) isDivision_OneOf() {}

func (*Division_Procedure) isDivision_OneOf() {}

type Identification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Identification) Reset() {
	*x = Identification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identification) ProtoMessage() {}

func (x *Identification) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identification.ProtoReflect.Descriptor instead.
func (*Identification) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{4}
}

type Paragraph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOf:
	//
	//	*Paragraph_ProgramId_
	//	*Paragraph_Options_
	OneOf isParagraph_OneOf `protobuf_oneof:"one_of"`
}

func (x *Paragraph) Reset() {
	*x = Paragraph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paragraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paragraph) ProtoMessage() {}

func (x *Paragraph) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paragraph.ProtoReflect.Descriptor instead.
func (*Paragraph) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{5}
}

func (m *Paragraph) GetOneOf() isParagraph_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (x *Paragraph) GetProgramId() *Paragraph_ProgramId {
	if x, ok := x.GetOneOf().(*Paragraph_ProgramId_); ok {
		return x.ProgramId
	}
	return nil
}

func (x *Paragraph) GetOptions() *Paragraph_Options {
	if x, ok := x.GetOneOf().(*Paragraph_Options_); ok {
		return x.Options
	}
	return nil
}

type isParagraph_OneOf interface {
	isParagraph_OneOf()
}

type Paragraph_ProgramId_ struct {
	ProgramId *Paragraph_ProgramId `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3,oneof"`
}

type Paragraph_Options_ struct {
	Options *Paragraph_Options `protobuf:"bytes,99,opt,name=options,proto3,oneof"`
}

func (*Paragraph_ProgramId_) isParagraph_OneOf() {}

func (*Paragraph_Options_) isParagraph_OneOf() {}

type Environment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Environment) Reset() {
	*x = Environment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{6}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{7}
}

type Procedure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Procedure) Reset() {
	*x = Procedure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Procedure) ProtoMessage() {}

func (x *Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Procedure.ProtoReflect.Descriptor instead.
func (*Procedure) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{8}
}

type ArithmeticClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOf:
	//
	//	*ArithmeticClause_Native
	//	*ArithmeticClause_Standard
	OneOf isArithmeticClause_OneOf `protobuf_oneof:"one_of"`
}

func (x *ArithmeticClause) Reset() {
	*x = ArithmeticClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArithmeticClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArithmeticClause) ProtoMessage() {}

func (x *ArithmeticClause) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArithmeticClause.ProtoReflect.Descriptor instead.
func (*ArithmeticClause) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{9}
}

func (m *ArithmeticClause) GetOneOf() isArithmeticClause_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (x *ArithmeticClause) GetNative() bool {
	if x, ok := x.GetOneOf().(*ArithmeticClause_Native); ok {
		return x.Native
	}
	return false
}

func (x *ArithmeticClause) GetStandard() bool {
	if x, ok := x.GetOneOf().(*ArithmeticClause_Standard); ok {
		return x.Standard
	}
	return false
}

type isArithmeticClause_OneOf interface {
	isArithmeticClause_OneOf()
}

type ArithmeticClause_Native struct {
	Native bool `protobuf:"varint,1,opt,name=native,proto3,oneof"`
}

type ArithmeticClause_Standard struct {
	Standard bool `protobuf:"varint,2,opt,name=standard,proto3,oneof"`
}

func (*ArithmeticClause_Native) isArithmeticClause_OneOf() {}

func (*ArithmeticClause_Standard) isArithmeticClause_OneOf() {}

type EntryConventionClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryConventionName string `protobuf:"bytes,1,opt,name=entry_convention_name,json=entryConventionName,proto3" json:"entry_convention_name,omitempty"`
}

func (x *EntryConventionClause) Reset() {
	*x = EntryConventionClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryConventionClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryConventionClause) ProtoMessage() {}

func (x *EntryConventionClause) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryConventionClause.ProtoReflect.Descriptor instead.
func (*EntryConventionClause) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{10}
}

func (x *EntryConventionClause) GetEntryConventionName() string {
	if x != nil {
		return x.EntryConventionName
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Source_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Source_Type" json:"type,omitempty"`
	Content string      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{11}
}

func (x *Source) GetType() Source_Type {
	if x != nil {
		return x.Type
	}
	return Source_CODE
}

func (x *Source) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Paragraph_ProgramId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgramName string                     `protobuf:"bytes,1,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	Literal     string                     `protobuf:"bytes,2,opt,name=literal,proto3" json:"literal,omitempty"`
	Types       []Paragraph_ProgramId_Type `protobuf:"varint,3,rep,packed,name=types,proto3,enum=pb.Paragraph_ProgramId_Type" json:"types,omitempty"`
}

func (x *Paragraph_ProgramId) Reset() {
	*x = Paragraph_ProgramId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paragraph_ProgramId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paragraph_ProgramId) ProtoMessage() {}

func (x *Paragraph_ProgramId) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paragraph_ProgramId.ProtoReflect.Descriptor instead.
func (*Paragraph_ProgramId) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Paragraph_ProgramId) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *Paragraph_ProgramId) GetLiteral() string {
	if x != nil {
		return x.Literal
	}
	return ""
}

func (x *Paragraph_ProgramId) GetTypes() []Paragraph_ProgramId_Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type Paragraph_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arithmetic      []*ArithmeticClause      `protobuf:"bytes,1,rep,name=arithmetic,proto3" json:"arithmetic,omitempty"`
	EntryConvention []*EntryConventionClause `protobuf:"bytes,2,rep,name=entry_convention,json=entryConvention,proto3" json:"entry_convention,omitempty"`
}

func (x *Paragraph_Options) Reset() {
	*x = Paragraph_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cobol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paragraph_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paragraph_Options) ProtoMessage() {}

func (x *Paragraph_Options) ProtoReflect() protoreflect.Message {
	mi := &file_cobol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paragraph_Options.ProtoReflect.Descriptor instead.
func (*Paragraph_Options) Descriptor() ([]byte, []int) {
	return file_cobol_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Paragraph_Options) GetArithmetic() []*ArithmeticClause {
	if x != nil {
		return x.Arithmetic
	}
	return nil
}

func (x *Paragraph_Options) GetEntryConvention() []*EntryConventionClause {
	if x != nil {
		return x.EntryConvention
	}
	return nil
}

var File_cobol_proto protoreflect.FileDescriptor

var file_cobol_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x62, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x3d, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x29, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73,
	0x22, 0x37, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x6e,
	0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x64, 0x69, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55,
	0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x22, 0xd6, 0x01, 0x0a, 0x08, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a,
	0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x2d, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75,
	0x72, 0x65, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xed, 0x03, 0x0a, 0x09,
	0x50, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x63,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xe0, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61,
	0x6c, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f,
	0x4d, 0x4d, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41,
	0x4d, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x43, 0x55, 0x52, 0x53, 0x49, 0x56, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x04, 0x1a, 0x85, 0x01, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x61, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65,
	0x74, 0x69, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52,
	0x0a, 0x61, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x12, 0x44, 0x0a, 0x10, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65,
	0x52, 0x0f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x08, 0x0a, 0x06, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x22, 0x0d, 0x0a, 0x0b, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x22,
	0x54, 0x0a, 0x10, 0x41, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x43, 0x6c, 0x61,
	0x75, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x6f,
	0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x22, 0x4b, 0x0a, 0x15, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x15, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x71, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45,
	0x42, 0x55, 0x47, 0x10, 0x02, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x73, 0x61, 0x77, 0x69, 0x6e, 0x64, 0x2f, 0x63, 0x6f,
	0x62, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cobol_proto_rawDescOnce sync.Once
	file_cobol_proto_rawDescData = file_cobol_proto_rawDesc
)

func file_cobol_proto_rawDescGZIP() []byte {
	file_cobol_proto_rawDescOnce.Do(func() {
		file_cobol_proto_rawDescData = protoimpl.X.CompressGZIP(file_cobol_proto_rawDescData)
	})
	return file_cobol_proto_rawDescData
}

var file_cobol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cobol_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cobol_proto_goTypes = []interface{}{
	(Paragraph_ProgramId_Type)(0), // 0: pb.Paragraph.ProgramId.Type
	(Source_Type)(0),              // 1: pb.Source.Type
	(*CompilationGroup)(nil),      // 2: pb.CompilationGroup
	(*CompilationUnit)(nil),       // 3: pb.CompilationUnit
	(*SourceUnit)(nil),            // 4: pb.SourceUnit
	(*Division)(nil),              // 5: pb.Division
	(*Identification)(nil),        // 6: pb.Identification
	(*Paragraph)(nil),             // 7: pb.Paragraph
	(*Environment)(nil),           // 8: pb.Environment
	(*Data)(nil),                  // 9: pb.Data
	(*Procedure)(nil),             // 10: pb.Procedure
	(*ArithmeticClause)(nil),      // 11: pb.ArithmeticClause
	(*EntryConventionClause)(nil), // 12: pb.EntryConventionClause
	(*Source)(nil),                // 13: pb.Source
	(*Paragraph_ProgramId)(nil),   // 14: pb.Paragraph.ProgramId
	(*Paragraph_Options)(nil),     // 15: pb.Paragraph.Options
}
var file_cobol_proto_depIdxs = []int32{
	3,  // 0: pb.CompilationGroup.units:type_name -> pb.CompilationUnit
	4,  // 1: pb.CompilationUnit.units:type_name -> pb.SourceUnit
	5,  // 2: pb.SourceUnit.divisions:type_name -> pb.Division
	4,  // 3: pb.SourceUnit.units:type_name -> pb.SourceUnit
	13, // 4: pb.SourceUnit.sources:type_name -> pb.Source
	6,  // 5: pb.Division.identification:type_name -> pb.Identification
	8,  // 6: pb.Division.environment:type_name -> pb.Environment
	9,  // 7: pb.Division.data:type_name -> pb.Data
	10, // 8: pb.Division.procedure:type_name -> pb.Procedure
	14, // 9: pb.Paragraph.program_id:type_name -> pb.Paragraph.ProgramId
	15, // 10: pb.Paragraph.options:type_name -> pb.Paragraph.Options
	1,  // 11: pb.Source.type:type_name -> pb.Source.Type
	0,  // 12: pb.Paragraph.ProgramId.types:type_name -> pb.Paragraph.ProgramId.Type
	11, // 13: pb.Paragraph.Options.arithmetic:type_name -> pb.ArithmeticClause
	12, // 14: pb.Paragraph.Options.entry_convention:type_name -> pb.EntryConventionClause
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cobol_proto_init() }
func file_cobol_proto_init() {
	if File_cobol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cobol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompilationGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompilationUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Division); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paragraph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Environment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Procedure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArithmeticClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryConventionClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paragraph_ProgramId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cobol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paragraph_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cobol_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Division_Identification)(nil),
		(*Division_Environment)(nil),
		(*Division_Data)(nil),
		(*Division_Procedure)(nil),
	}
	file_cobol_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Paragraph_ProgramId_)(nil),
		(*Paragraph_Options_)(nil),
	}
	file_cobol_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ArithmeticClause_Native)(nil),
		(*ArithmeticClause_Standard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cobol_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cobol_proto_goTypes,
		DependencyIndexes: file_cobol_proto_depIdxs,
		EnumInfos:         file_cobol_proto_enumTypes,
		MessageInfos:      file_cobol_proto_msgTypes,
	}.Build()
	File_cobol_proto = out.File
	file_cobol_proto_rawDesc = nil
	file_cobol_proto_goTypes = nil
	file_cobol_proto_depIdxs = nil
}
